services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    networks:
      - angiday-network
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: angiday_dev
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping" ]
      interval: 10s
      timeout: 5s
      retries: 10

  eureka-service:
    container_name: eureka-service
    build:
      context: eureka-service/
      dockerfile: Dockerfile
    restart: on-failure
    networks:
      - angiday-network
    ports:
      - "8761:8761"

  api-gateway:
    container_name: api-gateway
    build:
      context: api-gateway/
      dockerfile: Dockerfile
    restart: on-failure
    networks:
      - angiday-network
    depends_on:
      - eureka-service
    ports:
      - "8080:8080"
    env_file:
      - .env.dev

  user-service:
    container_name: user-service
    build:
      context: user-service/
      dockerfile: Dockerfile
    restart: always
    networks:
      - angiday-network
    depends_on:
      - mysql
      - eureka-service
    env_file:
      - .env.dev

networks:
  angiday-network:
    driver: bridge