spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filter:
        - RewritePath=/api/v1/.*?/(?<remaining>.*), /$\{remaining}
      mvc:
        routes:
          - id: demo-route
            uri: lb://USER-SERVICE
            predicates:
              - Path=/api/v1/demo/**
            filters:
              - StripPrefix=2
          - id: auth-route
            uri: lb://USER-SERVICE
            predicates:
              - Path=/api/v1/auth/**
            filters:
              - StripPrefix=2

server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka}

auth-service:
  url: ${AUTH_SERVICE_URL:http://localhost:8080/api/v1/auth}
