name: angiday Microservices CI with Maven

on:
  pull_request:
    branches:
      - 'main'

env:
  DATABASE_TEST_URL: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  DATABASE_TEST_USERNAME: root
  DATABASE_TEST_PASSWORD: 123456

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: { dir: [
        'user-service'
      ]}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B clean install --file pom.xml -DskipTests
        working-directory: ${{matrix.dir}}

  test:
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: 123456
        ports:
          - "3306:3306"
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 10
    runs-on: ubuntu-latest
    needs:
      - build
    strategy:
      matrix: { dir: [
        'user-service'
      ] }
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run unit test
        run: mvn -f pom.xml test
        working-directory: ${{matrix.dir}}
