name: angiday Microservices CI with Docker

on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'

jobs:
  docker-build:
    name: Build and push Docker image to Dockerhub
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    strategy:
      matrix: { dir: [
        'user-service',
        'api-gateway',
        'eureka-service'
      ] }
    permissions:
      contents: read
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:${{ matrix.dir }}"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/angiday-${{ matrix.dir }}:${{ github.sha }}
